### ISSUE TITLE
In `sector_classifications` the values of `sector` should be lowercase

### ISSUE THREAD

**Issue by daisy-pacheco** [2DegreesInvesting/r2dii.data#222] opened 2021-02-25 08:33 UTC
Hello all! @maurolepore @jdhoffa @georgeharris2deg 

We are experiencing a weird issue when doing the matching process with one of the banks we are working with. This is happening when we use the PSIC sector bridge that has been recently uploaded to CRAN.

The problem we have is that we have no matches when using this sector classification system. If we try to do the matches using the NACE codes, it would work normally. Do you happen to have any idea on what could be going wrong?

Thanks for your time!!!
Daisy

---
I attach the lbk_demo I'm using.

[lbk_demo.csv.zip](https://github.com/2DegreesInvesting/r2dii.data/files/6041570/lbk_demo.csv.zip)

The reprex of the error is the following, although in the Console the actual error that pops up is: 

<img width="491" alt="Screenshot 2021-02-25 at 09 22 35" src="https://user-images.githubusercontent.com/55544124/109124265-02504680-774b-11eb-97d5-fe174f5ef4c8.png">

```r
lbk_demo <- r2dii.data::loanbook_demo

write.csv(lbk_demo, "lbk_demo.csv")

# What I'm doing here is:
# 1- changing the sector_classification_system column to PSIC and 
# 2- manually changing the code for oil&gas from 610 (NACE) to 6100 (PSIC)
lbk_demo_psic <- readr::read_csv("lbk_demo.csv")

ald_demo <- r2dii.data::ald_demo

matches <- r2dii.match::match_name(lbk_demo_psic, ald_demo)
#> Error in dplyr::groups(loanbook): object 'lbk_demo_psic' not found
```

**Comment by maurolepore** [comment] 2021-02-25 16:32
Thanks @daisy-pacheco 

I'm sorry the problem persists but I'm also glad because it exposes a much bigger problem I hope we'll soon dress. A big sorry for intruding this focused conversation with my agenda about the bigger problem. But it is an excellent example of the point I am trying to make.

Consider the conversation that lead to the latest release:

@jdhoffa:

> The package just needs to be released as a user is missing classification codes and cant proceed with their analysis

Me:

> I'm happy to do it if you think it's the way to go but I kindly disagree. Let me explain.

> I have not seen a reprex so I can't be sure that will fix the problem. This smell similar to the situation we have in r2dii.analysis -- where "we think" we are fixing the user's problem but we are not. 

> Ultimately, I am noticing a pattern that seems not not help neither the users nor the maintainers. Maybe we need to discuss this in a call?

To understand the ultimate problem let me use an analogy.

#### The problem

You feel sick and go to the doctor. You tell your doctor what sickness you think you have and the medicine you think you need. 
Your doctor does not order any further examination. She gives you the medicine you asked for and gets you out of way quickly and happily.

Is this a good way to treat you? You may think it is, until you realize that you remain sick. 

#### The solution

You and your doctor bite the bullet. You keep examining your problem until you are sure what the problem and solution are. In the beginning, this may feel too slow, but in the long run everyone is healthier and save a ton of time going back and forth to the doctors office.

#### What this means for an R package maintainer like me

What I wrote above explores the perspective of the user and product owner (the sick person). Now let me explain a bit the perspective of the maintainer. Every time the maintainer of an R packages submits an update to CRAN they sign a policy that includes the following:

> Submitting updates should be done responsibly and with respect for the volunteers’ time. Once a package is established (which may take several rounds), “no more than every 1–2 months” seems appropriate.
-- https://cran.r-project.org/web/packages/policies.html

#### The good news

The good news is that Jackson already organized a meeting to explain this problem to you, @georgeharris2deg, and Maarten. In that meeting I will likely point to this comment.

**Comment by daisy-pacheco** [comment] 2021-02-26 07:28
Hi @maurolepore 

Thank you for your answer, and for the very comprehensive explanation of the bigger picture of this issue. I totally understand what you mean, and I'm sorry we did not follow the right order of things...

I will definitely participate in the meeting you mention, it's such a great opportunity to understand better the processes and the best practices we should be implementing, so we are all in the same page and don't have to go back and forth on issues.

In the meantime, do you have an idea of what the problem could be? We have the next meeting with our partner on Tuesday morning, and it could be helpful to have an idea of what's the problem and how can it be solved,  so we can plan the session accordingly.

Many thanks again for your time!

**Comment by maurolepore** [comment] 2021-02-26 13:42
Great you'll join the meeting :+1: 

The way the "big picture" problem suggests I can help you with this specific problem is by asking you or the partner for a reproducible example with the [reprex package](https://reprex.tidyverse.org/) (reprex for short). Compared to any example, an example with the reprex package has [properties that make the process most effective](https://reprex.tidyverse.org/articles/reprex-dos-and-donts.html#package-philosophy).

As the doctor of the analogy, we (maintainers) intend to help fix the problem as quickly as possible. We truly wish we could understand the problem and guess exactly how to expose it without bothering users. But unfortunately we can't, and the quickest way is to bite the bullet and develop a reproducible example with the reprex package.

We know that [this seems like a lot of work](https://reprex.tidyverse.org/articles/reprex-dos-and-donts.html#this-seems-like-a-lot-of-work). Commonly the responsibility of developing a useful reprex falls completely on the user because it's in their best interest to fix their own problem. In our case, however, we are willing to help. We don't just say "go figure it out" but instead we say "let's do this together; it's going to hurt but we can the pain". 

So as I did before with @georgeharris2deg, I am happy to meet you in a coding helpdesk and help you develop a reprex. In turn, you can meet with the partner and help them develop a reprex.

**Comment by daisy-pacheco** [comment] 2021-02-26 14:38
Thanks @maurolepore 

I think that was what I did in my first message? I attached the file I used and I added the reprex for the error I'm having, which is exactly what we saw with our partner. Should I be more specific on the explanation of the issue? Or am I missing something important about the reprex process?

Otherwise I'd be happy to schedule a slot for your helpdesk. Thanks again!

**Comment by maurolepore** [comment] 2021-02-26 18:02
I noticed and thank you for that reprex. If you keep doing that you will get really good, make me very happy, and get answers super quick.

Yes, that reprex missed an important bit -- the part where you modified the default data to replace it with the data you care about. That is where most likely the problem is, and therefore the part that is most useful to show.

As an example I will walk you through the process I follow, and show you how illuminating it might be.

From your example I learn that we need to focus on `sector_classifications` where `sector` is "Oil and Gas" and `code` is `6100`. Let's do that and exclude the noisy rest.

``` r
library(r2dii.data)
library(dplyr)

sector_classifications %>% filter(code == 6100)
#> # A tibble: 2 x 4
#>   sector      borderline code  code_system
#>   <chr>       <lgl>      <chr> <chr>      
#> 1 oil and gas FALSE      6100  NACE       
#> 2 Oil and Gas FALSE      6100  PSIC

# For any `code_system` the value of `sector` is lowercase -- except for PSIC
sector_classifications %>% 
  filter(code_system != "PSIC") %>% 
  pull(sector) %>% 
  unique()
#>  [1] "not in scope" "automotive"   "steel"        "oil and gas"  "power"       
#>  [6] "shipping"     "aviation"     "cement"       "coal"         NA

sector_classifications %>% 
  filter(code_system == "PSIC") %>% 
  pull(sector) %>% 
  unique()
#> [1] "not in scope" "Coal"         "Oil and Gas"  "Cement"       "Steel"       
#> [6] "Automotive"   "Power"        "Shipping"     "Aviation"
```

<sup>Created on 2021-02-26 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

I immediately notice that for any `code_system` the value of `sector` is lowercase -- except for PSIC. I'm not sure  that is indeed the problem but gets me close. I'll do some more experiments and post here another reprex.

----

For the record, we run two relevant ds-incubator meetups about how to have productive conversations about code:

* https://youtu.be/4IXcu1g0zfk
* https://youtu.be/H4ucsYPrC0g

**Comment by maurolepore** [comment] 2021-02-26 20:33
Here is my follow up. It confirms that the problem is this: In `sector_classifications` the values of `sector` should be lowercase.
 
``` r
library(dplyr, warn.conflicts = FALSE)
library(r2dii.data)
# https://github.com/2DegreesInvesting/r2dii.match/pull/354
devtools::load_all()
#> ℹ Loading r2dii.match

# Smallest dataset possible that will expose the problem and solution
loanbook <- tibble::tribble(
  ~id_ultimate_parent, ~name_ultimate_parent, ~id_direct_loantaker, ~name_direct_loantaker, ~sector_classification_system, ~sector_classification_direct_loantaker,
  "UP51",     "Cercl Mining Bv",               "C118",  "Madalena Energy Inc",                        "PSIC",                                    6100
)

bad <- tibble::tribble(
  ~sector,       ~borderline,  ~code, ~code_system,
  "Oil and Gas",        TRUE, "6100",       "PSIC",
)

# EXPOSE PROBLEM
# Allows using the `bad` sector_classifications inside match_name()
op <- list(r2dii.match.sector_classifications = bad)
restore <- options(op)
# Expect  no match
match_name(loanbook, ald_demo)
#> Warning: Found no match.
#> # A tibble: 0 x 15
#> # … with 15 variables: id_ultimate_parent <chr>, name_ultimate_parent <chr>,
#> #   id_direct_loantaker <chr>, name_direct_loantaker <chr>,
#> #   sector_classification_system <chr>,
#> #   sector_classification_direct_loantaker <dbl>, id_2dii <lgl>, level <lgl>,
#> #   sector <lgl>, sector_ald <lgl>, name <lgl>, name_ald <lgl>, score <lgl>,
#> #   source <lgl>, borderline <lgl>

# SHOW SOLUTION
# Allows using the `good` sector_classifications inside match_name()
good <- tibble::tribble(
  ~sector,       ~borderline,  ~code, ~code_system,
  "oil and gas",        TRUE, "6100",       "PSIC",
)
op <- list(r2dii.match.sector_classifications = good)
restore <- options(op)
# Expect  match
match_name(loanbook, ald_demo)
#> # A tibble: 2 x 15
#>   id_ultimate_parent name_ultimate_parent id_direct_loantak… name_direct_loanta…
#>   <chr>              <chr>                <chr>              <chr>              
#> 1 UP51               Cercl Mining Bv      C118               Madalena Energy Inc
#> 2 UP51               Cercl Mining Bv      C118               Madalena Energy Inc
#> # … with 11 more variables: sector_classification_system <chr>,
#> #   sector_classification_direct_loantaker <dbl>, id_2dii <chr>, level <chr>,
#> #   sector <chr>, sector_ald <chr>, name <chr>, name_ald <chr>, score <dbl>,
#> #   source <chr>, borderline <lgl>

options(restore)
```

<sup>Created on 2021-02-26 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

---

The pull request https://github.com/2DegreesInvesting/r2dii.match/pull/354 allows users to inject a custom `sector_classifications` for `match_name()` to use. So a temporary solution is to install that pull request, and inject a custom `sector_classifications` where `sector` is the lowercase version of `r2dii.data::sector_classifications$sector`.

* The next releasee of r2dii.data will fix the incorrect `sector_classifications`. 
* The next release of r2dii.match will likely allow users to inject a custom `sector_classifications`. The exact implementation may be different to that of https://github.com/2DegreesInvesting/r2dii.match/pull/354 because @jdhoffa has a different idea.

**Comment by maurolepore** [comment] 2021-02-27 15:14
Here is a reprex that shows that the problem is now fixed via #223.

``` r
# After https://github.com/2DegreesInvesting/r2dii.data/pull/223
sort(unique(r2dii.data::sector_classifications$sector))
#> [1] "automotive"   "aviation"     "cement"       "coal"         "not in scope"
#> [6] "oil and gas"  "power"        "shipping"     "steel"
```

<sup>Created on 2021-02-27 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Closed** 2021-02-27 16:54 UTC
Labels: bug

**Comment by maurolepore** [comment] 2021-03-01 21:27
r2dii.data v0.1.9 is now on CRAN. Unfortunately we could not make it before the meeting with your stakeholder today. CRAN adds friction for updates that are too close to a previous one. 

This reprex shows evidence that the problem reported here is now fixed:

``` r
# install.packages("r2dii.data", repos = "https://cran.r-project.org/")
library("r2dii.data")
library("r2dii.match")
packageVersion("r2dii.data")
#> [1] '0.1.9'
packageVersion("r2dii.match")
#> [1] '0.0.8.9000'

loanbook_psic <- vroom::vroom("~/Downloads/lbk_demo.csv.zip")
#> Multiple files in zip: reading 'lbk_demo.csv'
#> Rows: 321
#> Columns: 19
#> Delimiter: ","
#> chr [13]: id_loan, id_direct_loantaker, name_direct_loantaker, id_intermediate_parent_1, n...
#> dbl [ 3]: loan_size_outstanding, loan_size_credit_limit, sector_classification_direct_loan...
#> lgl [ 3]: name_project, lei_direct_loantaker, isin_direct_loantaker
#> 
#> Use `spec()` to retrieve the guessed column specification
#> Pass a specification to the `col_types` argument to quiet this message
match_name(loanbook_psic, r2dii.data::ald_demo)
#> # A tibble: 68 x 28
#>    id_loan id_direct_loanta… name_direct_loan… id_intermediate… name_intermedia…
#>    <chr>   <chr>             <chr>             <chr>            <chr>           
#>  1 L276    C118              Madalena Energy … <NA>             <NA>            
#>  2 L276    C118              Madalena Energy … <NA>             <NA>            
#>  3 L277    C114              Krisenergy Ltd    <NA>             <NA>            
#>  4 L278    C107              Jerusalem Oil Ex… <NA>             <NA>            
#>  5 L278    C107              Jerusalem Oil Ex… <NA>             <NA>            
#>  6 L279    C147              Naphtha Israel P… <NA>             <NA>            
#>  7 L280    C151              Panoro Energy Asa <NA>             <NA>            
#>  8 L280    C151              Panoro Energy Asa <NA>             <NA>            
#>  9 L281    C194              Sunshine Oilsand… <NA>             <NA>            
#> 10 L281    C194              Sunshine Oilsand… <NA>             <NA>            
#> # … with 58 more rows, and 23 more variables: id_ultimate_parent <chr>,
#> #   name_ultimate_parent <chr>, loan_size_outstanding <dbl>,
#> #   loan_size_outstanding_currency <chr>, loan_size_credit_limit <dbl>,
#> #   loan_size_credit_limit_currency <chr>, sector_classification_system <chr>,
#> #   sector_classification_input_type <chr>,
#> #   sector_classification_direct_loantaker <dbl>, fi_type <chr>,
#> #   flag_project_finance_loan <chr>, name_project <lgl>,
#> #   lei_direct_loantaker <lgl>, isin_direct_loantaker <lgl>, id_2dii <chr>,
#> #   level <chr>, sector <chr>, sector_ald <chr>, name <chr>, name_ald <chr>,
#> #   score <dbl>, source <chr>, borderline <lgl>
```

<sup>Created on 2021-03-01 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by daisy-pacheco** [comment] 2021-03-02 10:19
Thank you so much @maurolepore for this!!!
